# Generated by Django 3.2.7 on 2021-09-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Ubicacion', models.CharField(max_length=100)),
                ('Capacidad_Individual', models.IntegerField()),
                ('Capacidad_Salas', models.IntegerField()),
                ('Servicios_Adicionales', models.CharField(max_length=500)),
                ('Precio', models.FloatField()),
                ('Cantidad_Ind_Disponible', models.IntegerField()),
                ('Cantidad_Ind_Ocupada', models.IntegerField()),
                ('Cantidad_Salas_Disponible', models.IntegerField()),
                ('Cantidad_Salas_Ocupada', models.IntegerField()),
                ('Valoracion_Clientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala_COW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdSala', models.IntegerField()),
                ('Fecha_Renta', models.DateField()),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_COW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPuesto', models.IntegerField()),
                ('Fecha_Renta', models.DateField()),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
            ],
        ),
    ]
