# Generated by Django 3.2.7 on 2021-09-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacion',
            name='Cantidad_Ind_Disponible',
        ),
        migrations.RemoveField(
            model_name='locacion',
            name='Cantidad_Ind_Ocupada',
        ),
        migrations.RemoveField(
            model_name='locacion',
            name='Cantidad_Salas_Disponible',
        ),
        migrations.RemoveField(
            model_name='locacion',
            name='Cantidad_Salas_Ocupada',
        ),
        migrations.RemoveField(
            model_name='locacion',
            name='Precio',
        ),
    ]
