# Generated by Django 3.2.7 on 2021-09-19 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20210918_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto_cow',
            name='Fecha_Renta',
        ),
        migrations.RemoveField(
            model_name='puesto_cow',
            name='IdPuesto',
        ),
        migrations.RemoveField(
            model_name='sala_cow',
            name='Fecha_Renta',
        ),
        migrations.RemoveField(
            model_name='sala_cow',
            name='IdSala',
        ),
        migrations.AddField(
            model_name='puesto_cow',
            name='Cantidad_Ind_Disponible',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puesto_cow',
            name='Cantidad_Ind_Ocupada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puesto_cow',
            name='Capacidad_Individual',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puesto_cow',
            name='Precio',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puesto_cow',
            name='Servicios_Adicionales',
            field=models.CharField(default='Cafeteria, Wifi, Bano', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala_cow',
            name='Cantidad_Salas_Disponible',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala_cow',
            name='Cantidad_Salas_Ocupada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala_cow',
            name='Capacidad_Salas',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala_cow',
            name='Precio',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala_cow',
            name='Servicios_Adicionales',
            field=models.CharField(default='Cafeteria, Wifi, Bano', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reserva_Sala_COW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Reserva', models.DateField()),
                ('Pago_Confirmado', models.BooleanField()),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
                ('IdSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.sala_cow')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Puesto_COW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Reserva', models.DateField()),
                ('Pago_Confirmado', models.BooleanField()),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
                ('IdPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.puesto_cow')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Reserva_Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_Pago', models.FloatField()),
                ('Fecha_Pago', models.DateField()),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
                ('IdReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.reserva_sala_cow')),
                ('IdSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.sala_cow')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Reserva_Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_Pago', models.FloatField()),
                ('Fecha_Pago', models.DateField()),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
                ('IdPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.puesto_cow')),
                ('IdReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.reserva_puesto_cow')),
            ],
        ),
    ]
