# Generated by Django 3.2.7 on 2021-10-01 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0004_auto_20210929_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capacidad', models.IntegerField(blank=True, null=True)),
                ('Servicios_Adicionales', models.CharField(max_length=500)),
                ('Precio', models.FloatField()),
                ('Disponible', models.BooleanField(blank=True, null=True)),
                ('IdLocacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.locacion')),
                ('idTipoLugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.tipolugar')),
            ],
        ),
    ]
