# Generated by Django 3.2.7 on 2021-10-01 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=300)),
                ('Apellidos', models.CharField(max_length=300)),
                ('Direccion', models.CharField(max_length=300)),
                ('Telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipousuario')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
