# Generated by Django 3.2.7 on 2021-10-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogo', '0005_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_ini_reserva', models.DateField(auto_now_add=True)),
                ('Fecha_fin_reserva', models.DateField(auto_now_add=True)),
                ('Pago_confirmado', models.BooleanField(blank=True, null=True)),
                ('Estado_reserva', models.BooleanField(blank=True, null=True)),
                ('idLugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_pago', models.FloatField(blank=True, null=True)),
                ('Fecha_pago', models.DateField(auto_now_add=True)),
                ('idReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renta.reserva')),
            ],
        ),
    ]
